### PR TITLE
insertion and deletion in singly, doubly and circular linked list at beginning, end and index position 

### PR DESCRIPTION
**Pull request by Arisha2902**

### CODE REVIEW

**Comment by Anuraj-IND** [comment]
@Arisha2902 fir se tag krna bhul gayi tu -_-

**Comment by Arisha2902** [comment]
@Anuraj-IND ,thanks for help

**Comment by Anuraj-IND** [comment]
> @Anuraj-IND ,thanks for help

Um who were you again ?

**Comment by Arisha2902** [comment]
Thanks sir , for helping me

**Pull request merged**
